name: Test Releases
on:
  push:
    branches:
      - development

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v4.0.0
        with:
          github-token: ${{ secrets.github_token }}
          version-file: './composer.json'
          tag-prefix: 'v'
          skip-version-file: 'true'
          skip-commit: 'true'
          skip-tag: 'true'
