name: Releases
on:
  push:
    branches:
      - 'release/*'

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v4.1.1
        with:
          github-token: ${{ secrets.github_token }}
          version-file: './composer.json'
          tag-prefix: 'v'
          create-summary: true
          skip-on-empty: false

      - name: create release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
